export const LANDING = '/';
export const SIGN_UP = '/signup';
export const SIGN_IN = '/signin';
export const HOME = '/home';
export const ACCOUNT = '/account';
export const ADMIN = '/admin';
export const JOB_SEARCH='/search';
export const PASSWORD_FORGET = '/pw-forget';
export const TRACK_MANAGE_APP = '/track_manage_application'
